"""add foreign key to onboarding

Revision ID: ae6728e4621e
Revises: 65d1d3e9c114
Create Date: 2024-10-18 12:34:33.749356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae6728e4621e'
down_revision = '65d1d3e9c114'
branch_labels = None
depends_on = None


# def upgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.add_column('onboardings', sa.Column('employee_id', sa.Integer(), nullable=True))
#     op.create_foreign_key(op.f('fk_onboardings_employee_id_employees'), 'onboardings', 'employees', ['employee_id'], ['id'])
#     # ### end Alembic commands ###


# def downgrade():
#     # ### commands auto generated by Alembic - please adjust! ###
#     op.drop_constraint(op.f('fk_onboardings_employee_id_employees'), 'onboardings', type_='foreignkey')
#     op.drop_column('onboardings', 'employee_id')
#     # ### end Alembic commands ###

def upgrade():
    # Commands to add a new column and foreign key to the existing table
    with op.batch_alter_table("onboardings") as batch_op:
        batch_op.add_column(sa.Column('employee_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_onboardings_employee_id_employees', 
            'employees', 
            ['employee_id'], 
            ['id']
        )

def downgrade():
    # Commands to remove the foreign key and column
    with op.batch_alter_table("onboardings") as batch_op:
        batch_op.drop_constraint('fk_onboardings_employee_id_employees', type_='foreignkey')
        batch_op.drop_column('employee_id')
